name: CMake Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libidn11-dev \      # Install the required library
            libcurl4-openssl-dev \  # Install Curl development files
            libssl-dev \        # Install OpenSSL development files
            build-essential      # Install build tools (gcc, g++, make, etc.)

      - name: Configure the project
        run: cmake -S . -B build

      - name: Build the project
        run: cmake --build build --target all  # Build all targets
